Repository codeit-sprint-fullstack/1-Sprint-Mission-FE, pull requests merged in 2024-10, with the labels that each got.

#137 [탁우현] sprint9
  .env
  .gitignore
  README.md
  components/Comment.jsx
  components/Header.jsx
  components/Pagination.jsx
  components/ProductList.jsx
  components/SearchBar.jsx
  contexts/authContext.js
  hooks/useFormValidation.js
  models/productModel.js
  next.config.mjs
  package-lock.json
  package.json
  pages/Articles/Registration.jsx
  pages/Articles/[id].jsx
  pages/Articles/index.jsx
  pages/Folder/index.jsx
  pages/Items/Registration.jsx
  pages/Items/[id].jsx
  pages/Items/index.jsx
  pages/Login.jsx
  pages/Products/Registration.jsx
  pages/Products/[id].jsx
  pages/Signup.jsx
  pages/_app.jsx
  pages/api/articles.js
  pages/api/auth.js
  pages/api/axios.js
  pages/api/comment.js
  pages/api/httpClient.js
  pages/api/products.js
  pages/api/user.js
  pages/index.jsx
  public/images/Img_inquiry_empty.png
  public/images/btn_visibility_24px.png
  public/images/ic_heart_liked.png
  styles/Home.module.css
  styles/alertModal.module.css
  styles/articles.module.css
  styles/comment.module.css
  styles/detailArticle.module.css
  styles/detailProduct.module.css
  styles/globals.css
  styles/header.module.css
  styles/login.module.css
  styles/products.module.css
  styles/registration.module.css
  styles/signup.module.css
  utils/queryClientOption.js
Labels: 최종 제출

#139 [강범준] sprint9
  .DS_Store
  .gitignore
  README.md
  api/api.js
  components/ArticleList.js
  components/BestArticleList.js
  components/CommentList.js
  components/CommentOptions.js
  components/CommentOptions.module.css
  components/DeleteConfirmModal.js
  components/DeleteConfirmModal.module.css
  components/Footer.js
  components/Footer.module.css
  components/Modal.js
  components/Modal.module.css
  components/Nav.js
  components/Nav.module.css
  components/ProductOptions.js
  components/ProductOptions.module.css
  components/SignupCompleteModal.js
  components/SignupCompleteModal.module.css
  lib/axios.js
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/api/axios.js
  pages/folder/folder.js
  pages/items/[itemId].js
  pages/items/create.js
  pages/items/index.js
  pages/login.js
  pages/market.js
  pages/registArticle.js
  pages/signup.js
  public/Img_inquiry_empty.png
  public/btn-heart.png
  public/eye.png
  public/eye2.png
  public/heart_filled.svg
  public/ic_check.png
  public/logo.png
  public/placeholder-image.jpg
  public/product_reply.svg
  styles/CreateItem.module.css
  styles/ItemDetail.module.css
  styles/Products.module.css
  styles/global.css
  styles/login.module.css
  styles/signup.module.css
  test.http
Labels: 최종 제출

#145 [안재민] Sprint9
  app/(nav-layout)/articles/[articleId]/page.jsx
  app/(nav-layout)/articles/[articleId]/page.module.css
  app/(nav-layout)/articles/create/page.jsx
  app/(nav-layout)/articles/page.jsx
  app/(nav-layout)/articles/page.module.css
  app/(nav-layout)/articles/patch/[articleId]/page.jsx
  app/(nav-layout)/items/[itemId]/page.jsx
  app/(nav-layout)/items/[itemId]/page.module.css
  app/(nav-layout)/layout.jsx
  app/(nav-layout)/page.jsx
  app/(nav-layout)/page.module.css
  app/(no-layout)/layout.jsx
  app/(no-layout)/login/page.jsx
  app/(no-layout)/login/page.module.css
  app/(no-layout)/signup/page.jsx
  app/(no-layout)/signup/page.module.css
  app/middleware.js
  package.json
  public/big-logo.svg
  public/google.svg
  public/kakao.svg
  public/visibility-off.svg
  public/visibility-on.svg
  src/entities/layout.js
  src/features/Nav.jsx
  src/hooks/Constant/queryKeys.js
  src/hooks/comment/useArticleComments.js
  src/hooks/comment/useCommentMutations.js
  src/hooks/form/useSignInMutation.js
  src/hooks/form/useSignupMutation.js
  src/hooks/useValidation/useFormValidation.js
  src/shared/components/Buttons/ActionButton.jsx
  src/shared/components/Buttons/ActionButton.module.css
  src/shared/components/Forms/FormFooter.jsx
  src/shared/components/Forms/FormFooter.module.css
  src/shared/components/Forms/LoginForm.jsx
  src/shared/components/Forms/LoginForm.module.css
  src/shared/components/Forms/SignupForm.jsx
  src/shared/components/Forms/SignupForm.module.css
  src/shared/components/article/CreateArticle.jsx
  src/shared/components/article/GeneralArticles.jsx
  src/shared/components/article/PatchArticle.jsx
  src/shared/components/article/comment/ArticleComment.jsx
  src/shared/components/comment/Comment.jsx
  src/shared/components/comment/Comment.module.css
  src/shared/components/comment/CommentInputBox.jsx
  src/shared/components/comment/CommentInputBox.module.css
  src/shared/components/comment/CommentQuery.js
  src/shared/components/comment/CommentTemplate.jsx
  src/shared/components/comment/CommentTemplate.module.css
  src/shared/components/inputs/Input.jsx
  src/shared/components/inputs/Input.module.css
  src/shared/components/inputs/InputErrorText.jsx
  src/shared/components/inputs/InputErrorText.module.css
  src/shared/store/auth/auth.js
  src/shared/store/form/login.js
  src/shared/store/form/signup.js
  src/utils/api/api.js
  src/utils/api/axios.js
  src/utils/api/codeit.js
Labels: 매운맛 🔥, 제출일 이후 제출한PR, 최종 제출

#148 [박성현] sprint9
  .env
  components/Pagination.js
  components/ProductCard.js
  components/ProductList.js
  components/articleCard.js
  components/aticleList.js
  components/comment.js
  components/header.js
  lib/Redirect.js
  lib/api.js
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/articles/[id].js
  pages/comment.js
  pages/forder.js
  pages/items.js
  pages/items/[id].js
  pages/login.js
  pages/modify/[id].js
  pages/signup.js
  public/btn_left.png
  public/btn_right.png
  public/btn_visibility_off.png
  public/btn_visibility_on.png
  public/google.png
  public/kakaotalk.png
  public/no_ask.png
  styles/Comment.module.css
  styles/Header.module.css
  styles/Login.module.css
  styles/Pagination.module.css
  styles/ProductCard.module.css
  styles/ProductList.module.css
  styles/Signup.module.css
  styles/global.css
  styles/itemDetail.module.css
  utils/formatDate.js
Labels: 제출일 이후 제출한PR, 최종 제출

#149 [송영섭] misson9
  .github/pull-request-template.md
  next-mission/components/authentication/AuthenticationBody.js
  next-mission/components/authentication/AuthenticationBody.module.css
  next-mission/components/authentication/AuthenticationButton.js
  next-mission/components/authentication/AuthenticationButton.module.css
  next-mission/components/authentication/EasyLogin.js
  next-mission/components/authentication/EasyLogin.module.css
  next-mission/components/authentication/InputBox.js
  next-mission/components/authentication/InputBox.module.css
  next-mission/components/particularPage/CommentFrom.js
  next-mission/components/particularPage/CommentList.js
  next-mission/components/particularPage/CommentList.module.css
  next-mission/components/particularPage/CommentListBody.js
  next-mission/components/particularPage/CommentListBody.module.css
  next-mission/components/particularPage/DropDown.js
  next-mission/components/particularPage/DropDown.module.css
  next-mission/components/particularPage/NoticeBoardParticularInfo.js
  next-mission/components/particularPage/NoticeBoardParticularInfo.module.css
  next-mission/components/particularPage/ProductInfo.js
  next-mission/components/particularPage/ProductInfo.module.css
  next-mission/components/particularPage/ProductIntroduction.js
  next-mission/components/particularPage/ProductIntroduction.module.css
  next-mission/components/particularPage/ProductParticularInfo.js
  next-mission/components/particularPage/ProductParticularInfo.module.css
  next-mission/components/particularPage/ProductTag.js
  next-mission/components/particularPage/ProductTag.module.css
  next-mission/components/particularPage/UserInfo.js
  next-mission/components/particularPage/UserInfo.module.css
  next-mission/components/public/Nav.js
  next-mission/lib/axios.js
  next-mission/lib/axiosCodeit.js
  next-mission/pages/_app.js
  next-mission/pages/freeNoticeBoard/[id].js
  next-mission/pages/items/[id].js
  next-mission/pages/items/index.js
  next-mission/pages/signin.js
  next-mission/pages/signup.js
  next-mission/public/images/Img_inquiry.svg
  next-mission/public/images/ic_eyes.svg
  next-mission/public/images/ic_google.svg
  next-mission/public/images/ic_kakao.svg
  next-mission/public/images/ic_slash_eyes.svg
Labels: 매운맛 🔥, 미완성 :sob:, 제출일 이후 제출한PR, 진행 중 🏃

#146 [박명준] Sprint9
  .gitignore
  README.md
  components/BoardComponent/Article.js
  components/BoardComponent/Article.module.css
  components/BoardComponent/ArticleList.js
  components/BoardComponent/ArticleList.module.css
  components/BoardComponent/BestArticle.js
  components/BoardComponent/BestArticle.module.css
  components/BoardComponent/DropDown.js
  components/BoardComponent/DropDown.module.css
  components/BoardComponent/Search.js
  components/BoardComponent/Search.module.css
  components/BoardDetail/ArticleDropDown.js
  components/BoardDetail/CommentDropDown.js
  components/BoardDetail/KebabDropDown.module.css
  components/CommentComponent/CommentList.js
  components/CommentComponent/CommentList.module.css
  components/CommentComponent/NoComment.js
  components/CommentComponent/NoComment.module.css
  components/CommentComponent/PostComment.js
  components/CommentComponent/PostComment.module.css
  components/Layout/Footer.js
  components/Layout/Footer.module.css
  components/Layout/Header.js
  components/Layout/Header.module.css
  components/SignCommon/LoginForm.js
  components/SignCommon/LoginForm.module.css
  components/SignCommon/Modal.js
  components/SignCommon/Modal.module.css
  components/SignCommon/SignUpForm.js
  context/authContext.js
  hook/useFormValidation.js
  images/defaultItem.png
  images/signLogo.png
  lib/authApi.js
  lib/axios.js
  lib/productApi.js
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/board.js
  pages/board/[id].js
  pages/items.js
  pages/items/[id].js
  pages/login.js
  pages/signup.js
  styles/ItemsDetail.module.css
  styles/Login.module.css
  test.http
Labels: 매운맛 🔥, 미완성 :sob:, 제출일 이후 제출한PR, 진행 중 🏃

#150 [탁우현] sprint10
  .env
  components/Comment.jsx
  components/DropdownList/DropdownData.jsx
  components/Header.jsx
  components/ProductList.jsx
  contexts/authContext.js
  hooks/useFormValidation.js
  next.config.mjs
  package-lock.json
  package.json
  pages/Articles/Registration.jsx
  pages/Articles/[id].jsx
  pages/Articles/index.jsx
  pages/Items/Registration.jsx
  pages/Items/[id].jsx
  pages/Items/index.jsx
  pages/Signup.jsx
  pages/_app.jsx
  pages/api/articles.js
  pages/api/auth.js
  pages/api/comment.js
  pages/api/httpClient.js
  pages/index.jsx
  public/images/ic_plus.png
  styles/registration.module.css
Labels: 최종 제출

#154 [주영은] sprint10
  .gitignore
  components/BestProductComponents/BestProducts.jsx
  components/BoardComponents/BestProduct.jsx
  components/BoardComponents/BoardList.jsx
  components/BoardComponents/BoardListItems.jsx
  components/BoardComponents/SearchBar.jsx
  components/BoardDetailComponents/BoardChat.jsx
  components/BoardDetailComponents/BoardDetailInfo.jsx
  components/BoardDetailComponents/BoardDetailInfo.module.css
  components/BoardDetailComponents/ChatItem.jsx
  components/CreateBoardComponents/CreateForm.jsx
  components/CreateBoardComponents/ImageUpload.jsx
  components/CreateBoardComponents/ImageUpload.module.css
  components/CreateProductComponents/CreateBtn.jsx
  components/CreateProductComponents/CreateForm.jsx
  components/CreateProductComponents/CreateForm.module.css
  components/CreateProductComponents/ImageUpload.jsx
  components/CreateProductComponents/ImageUpload.module.css
  components/EditBoardComponents/EditBoard.jsx
  components/EditBoardComponents/ImageUpload.jsx
  components/EditBoardComponents/ImageUpload.module.css
  components/EditProductComponents/EditBtn.jsx
  components/EditProductComponents/EditForm.jsx
  components/EditProductComponents/EditForm.module.css
  components/EditProductComponents/ImageUpload.jsx
  components/EditProductComponents/ImageUpload.module.css
  components/ItemComponents/ItemList.jsx
  components/ItemComponents/ItemList.module.css
  components/ItemDetailComponents/Chat.jsx
  components/ItemDetailComponents/Chat.module.css
  components/ItemDetailComponents/ItemChat.jsx
  components/ItemDetailComponents/ItemInfo.jsx
  components/ItemDetailComponents/ItemInfo.module.css
  components/LoginComponents/FormFooter.jsx
  components/ModalComponents/Modal.module.css
  components/SigninComponents/FormFooter.jsx
  hooks/useArticles.js
  hooks/useComments.js
  images/Img_inquiry_empty.png
  images/ic_plus.png
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.jsx
  pages/api/auth/[...nextauth].js
  pages/board/[id].jsx
  pages/board/edit/[id].jsx
  pages/board/index.jsx
  pages/items/[id].jsx
  utils/apiClient.js
  utils/apiEndpoint.js
  utils/articleApi.js
  utils/articleChatApi.js
  utils/productApi.js
  utils/productChatApi.js
Labels: 매운맛 🔥, 최종 제출

#157 [김민서] sprint10
  public/image/beach.jpeg
  public/image/delete.svg
  public/image/delete_round.svg
  public/image/image_delete.svg
  public/image/image_plus.svg
  public/image/image_round.svg
  src/api/articleApi.js
  src/api/authApi.js
  src/api/axiosInstance.js
  src/api/commentApi.js
  src/api/productApi.js
  src/components/BestPosts.js
  src/components/BestProducts.js
  src/components/BestProducts.module.css
  src/components/CommentEditModal.js
  src/components/CommentItem.js
  src/components/CommentKebabMenu.js
  src/components/ImageUpload.js
  src/components/ImageUpload.module.css
  src/components/PostItem.module.css
  src/components/ProductCommentForm.js
  src/components/ProductCommentKebabMenu.js
  src/components/ProductEditModal.js
  src/components/ProductEmptyComments.js
  src/pages/articles/[id].js
  src/pages/articles/create.js
  src/pages/articles/edit/[id].js
  src/pages/items/[itemId].js
  src/pages/items/index.js
  src/pages/items/registration.js
  src/pages/login.js
  src/styles/productRegistration.module.css
Labels: 최종 제출
