Repository codeit-sprint-fullstack/1-Sprint-Mission-FE, pull requests merged in 2024-09, with the labels that each got.

#120 [강범준] sprint8
  .DS_Store
  .eslintrc.json
  .gitignore
  README.md
  components/Article.js
  components/Article.module.css
  components/ArticleList.js
  components/ArticleList.module.css
  components/BestArticleCard.js
  components/BestArticleCard.module.css
  components/BestArticleList.js
  components/BestArticleList.module.css
  components/CommentList.js
  components/CommentList.module.css
  components/Footer.js
  components/Footer.module.css
  components/Nav.js
  components/Nav.module.css
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/api/axios.js
  pages/articles/[id].js
  pages/articles/registration.js
  pages/comment.js
  pages/index.js
  pages/modify/[id].js
  pages/registArticle.js
  public/Img_reply_empty.png
  public/btn-heart.png
  public/btn_medium.png
  public/card.png
  public/facebook-logo.svg
  public/favicon.ico
  public/frame1.png
  public/frame2.png
  public/group19.png
  public/ic_arrow_down.png
  public/ic_heart.png
  public/ic_kebab.png
  public/ic_profile.png
  public/ic_search.png
  public/img_badge.png
  public/instagram-logo.svg
  public/nothing_comment.png
  public/twitter-logo.svg
  public/youtube-logo.svg
  styles/Home.module.css
  styles/global.css
  styles/registArticle.module.css
  test.http
Labels: 진행 중 🏃

#124 [김민수] sprint 8
  .eslintrc.json
  .gitignore
  README.md
  components/BestItem/BestItem.js
  components/BestItem/BestItem.module.css
  components/Header/Header.js
  components/Header/Header.module.css
  components/articleModal/articleModal.js
  components/articleModal/articleModal.module.css
  components/commentModal/commentModal.js
  components/commentModal/commentModal.module.css
  components/footer/Footer.js
  components/footer/Footer.module.css
  components/postView/Postview.js
  components/postView/Postview.module.css
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/api/api.js
  pages/index.js
  pages/post/[id].js
  pages/post/create.css
  pages/post/create.js
  pages/post/id.module.css
  public/ItemImg.svg
  public/MyImg.svg
  public/bestItem.svg
  public/deleteImg.svg
  public/dropdown.svg
  public/facebook.svg
  public/instagram.svg
  public/kebab-btn.svg
  public/logo-img.svg
  public/logo.png
  public/search.svg
  public/twitter.svg
  public/youtube.svg
  styles/Home.module.css
  styles/reset.css
Labels: 매운맛 🔥, 최종 제출

#132 [박성현] sprint8
  .eslintrc.json
  .github/pull-request-template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  components/articleCard.js
  components/aticleList.js
  components/bestArticle.js
  components/bestArticleCard.js
  components/comment.js
  components/footer.js
  components/header.js
  jsconfig.json
  lib/axios.js
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/articles/[id].js
  pages/comment.js
  pages/index.js
  pages/modify/[id].js
  pages/registPage.js
  public/btn_heart.png
  public/btn_medium.png
  public/default_img.png
  public/ic_arrow_down.png
  public/ic_facebook.png
  public/ic_heart.png
  public/ic_instagram.png
  public/ic_kebab.png
  public/ic_profile.png
  public/ic_search.png
  public/ic_twitter.png
  public/ic_youtube.png
  public/img_badge.png
  public/logo.png
  public/no_comment.png
  styles/Article.module.css
  styles/ArticleCard.module.css
  styles/ArticleList.module.css
  styles/BestArticle.module.css
  styles/Comment.module.css
  styles/Footer.module.css
  styles/Header.module.css
  styles/Home.module.css
  styles/RegistPage.module.css
  styles/global.css
Labels: 최종 제출
