Repository codeit-sprint-fullstack/1-Sprint-Mission-FE, pull requests merged in 2024-07, with the labels that each got.

#29 [김대건] sprint1, sprint2
  README.md
  faq/index.html
  index.html
  items/index.html
  login/asset/Component 2.png
  login/asset/Component 3.png
  login/asset/logo.png
  login/index.html
  login/reset.css
  login/style.css
  main/asset/Img_home_bottom.png
  main/asset/btn_large.png
  main/asset/btn_small.png
  main/asset/ic_facebook.png
  main/asset/ic_instagram.png
  main/asset/ic_twitter.png
  main/asset/ic_youtube.png
  main/asset/panda_background.png
  main/asset/panda_face.png
  main/asset/pandalogo_text.png
  main/asset/searchPanda.png
  main/asset/signPanda.png
  main/asset/trustPanda.png
  main/asset/usePanda.png
  privacy/index.html
  reset.css
  signup/asset/Component 2.png
  signup/asset/Component 3.png
  signup/asset/logo.png
  signup/index.html
  signup/reset.css
  signup/style.css
  style.css
Labels: 매운맛🔥

#16 [김현우] sprint2
  Head_image.jpg
  Script/GNB.js
  Script/data.js
  Script/login_js.js
  Script/signup_js.js
  Script/validation_login.js
  Script/validation_signup.js
  faq/index.html
  images/Group22.png
  images/I1.png
  images/I2.png
  images/I3.png
  images/I4.png
  images/I5.png
  images/Mobilelogo.svg
  images/Opend_Eye.svg
  images/TheEye.png
  images/TheEyeOpen.png
  images/favicon.ico
  images/google.png
  images/headLogo.svg
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/kakao.png
  images/lilLogo.svg
  images/logo.svg
  images/logos.png
  images/pandalogo_for_login.png
  images/src_image.png
  index.html
  items/index.html
  login/index.html
  login/style_login.css
  netlify.txt
  privacy/privacy.html
  reset.css
  signup/index.html
  signup/style_signup.css
  style.css
Labels: 매운맛🔥

#6 [박명준] sprint 1, sprint 2
  .github/pull-request-template.md
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/blueBackground.png
  images/eye-close.png
  images/eye-show.png
  images/googleDirect.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/kakaoDirect.png
  images/login-error.png
  images/login-page.png
  images/logo.png
  images/logoImage.png
  images/main-page.png
  images/meta-tag.png
  images/mobile_index.html.png
  images/mobile_login.html.png
  images/mobile_signup.html.png
  images/signup-error.png
  images/signup-page.png
  images/tablet_index.html.png
  images/판다 얼굴.png
  index.html
  page/faq.html
  page/items.html
  page/login.html
  page/privacy.html
  page/signup.html
  readme.md
  script/login.js
  script/signup.js
  style/reset.css
  style/sign-common.css
  style/sign-up-only.css
  style/style.css
Labels: 매운맛🔥

#18 [정준호] sprint2
  README.md
  faq.html
  freenote.html
  index.html
  items.html
  login_page/globe.js
  login_page/images_login/google_icon.svg
  login_page/images_login/kakao_icon.svg
  login_page/images_login/main_logo.svg
  login_page/login.html
  login_page/public_images/btn_visibility_action.svg
  login_page/signup.html
  login_page/style_login/body_login.css
  login_page/style_login/globe_login.css
  login_page/style_login/sign_up_style.css
  main/images_main/banner/Img_home_01.svg
  main/images_main/banner/Img_home_02.svg
  main/images_main/banner/Img_home_03.svg
  main/images_main/banner/Img_home_bottom.svg
  main/images_main/banner/Img_home_top.svg
  main/images_main/icon/ic_facebook.svg
  main/images_main/icon/ic_instagram.svg
  main/images_main/icon/ic_twitter.svg
  main/images_main/icon/ic_youtube.svg
  main/images_main/panda_market_logo.svg
  main/style_main/banner_style.css
  main/style_main/footer_style.css
  main/style_main/glober_style.css
  main/style_main/header_style.css
  main/style_main/reset.css
  pre_owned.html
  privacy.html
  sign_up/style_sign_up/body_sign_up.css
  sign_up/style_sign_up/globe_sign_up.css
Labels: 매운맛🔥

#30 [박상훈] sprint1, sprint2
  README.md
  faq.html
  imgs/Group_19.png
  imgs/Img_home_01.png
  imgs/Img_home_02.png
  imgs/Img_home_03.png
  imgs/Img_home_bottom.png
  imgs/Img_home_top.png
  imgs/btn_visibility_off.png
  imgs/btn_visibility_on.png
  imgs/google.png
  imgs/ic_facebook.png
  imgs/ic_instagram.png
  imgs/ic_twitter.png
  imgs/ic_youtube.png
  imgs/kakao.png
  index.html
  items.html
  login.html
  privacy.html
  reset.css
  signup.html
  style.css
Labels: 매운맛🔥

#3 [주영은] sprint1, sprint2
  .github/pull-request-template.md
  README.md
  common/login_signup.js
  html/faq.html
  html/items.html
  html/login.html
  html/privacy.html
  html/signup.html
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_topas.png
  image/eye-btn.png
  image/eye-show.png
  image/google-img.png
  image/ic_facebook.png
  image/ic_instagram.png
  image/ic_twitter.png
  image/ic_youtube.png
  image/index_html.png
  image/kakao-img.png
  image/login_html.png
  image/logo.svg
  image/signup_html.png
  index.html
  index.js
  js/login.js
  js/signup.js
  style/loginstyle.css
  style/reset.css
  style/signupstyle.css
  style/style.css
Labels: 순한맛🐑

#20 [송영섭] sprint 1 + 2
  README.md
  mission/faq/index.html
  mission/img/Group 19.png
  mission/img/Group 19.png:Zone.Identifier
  mission/img/Img_home_01.png
  mission/img/Img_home_01.png:Zone.Identifier
  mission/img/Img_home_02.png
  mission/img/Img_home_02.png:Zone.Identifier
  mission/img/Img_home_03.png
  mission/img/Img_home_03.png:Zone.Identifier
  mission/img/Img_home_bottom.png
  mission/img/Img_home_bottom.png:Zone.Identifier
  mission/img/Img_home_top.png
  mission/img/Img_home_top.png:Zone.Identifier
  mission/img/ic_facebook.png
  mission/img/ic_facebook.png:Zone.Identifier
  mission/img/ic_instagram.png
  mission/img/ic_instagram.png:Zone.Identifier
  mission/img/ic_twitter.png
  mission/img/ic_twitter.png:Zone.Identifier
  mission/img/ic_youtube.png
  mission/img/ic_youtube.png:Zone.Identifier
  mission/img/logo.png
  mission/img/logo.png:Zone.Identifier
  mission/index.html
  mission/item/index.html
  mission/login/img/Component 2.png
  mission/login/img/Component 2.png:Zone.Identifier
  mission/login/img/Component 3.png
  mission/login/img/Component 3.png:Zone.Identifier
  mission/login/img/logo.png
  mission/login/img/logo.png:Zone.Identifier
  mission/login/index.html
  mission/login/mobile_style.css
  mission/login/reset.css
  mission/login/script.js
  mission/login/style.css
  mission/mobile_style.css
  mission/pc_style.css
  mission/privacy/index.html
  mission/reset.css
  mission/signup/img/Component 2.png
  mission/signup/img/Component 2.png:Zone.Identifier
  mission/signup/img/Component 3.png
  mission/signup/img/Component 3.png:Zone.Identifier
  mission/signup/img/logo.png
  mission/signup/img/logo.png:Zone.Identifier
  mission/signup/index.html
  mission/signup/mobile_style.css
  mission/signup/reset.css
  mission/signup/script.js
  mission/signup/style.css
  mission/style.css
  mission/tablet_style.css
Labels: 순한맛🐑

#17 [임송이] Sprint 1, 2
  README.md
  faq/index.html
  img/Img_home_01.svg
  img/Img_home_02.svg
  img/Img_home_03.svg
  img/Img_home_bottom.svg
  img/Img_home_top.svg
  img/btn_visibility_off_24px.svg
  img/btn_visibility_on_24px.svg
  img/favicon.svg
  img/ic_facebook.svg
  img/ic_google.svg
  img/ic_instagram.svg
  img/ic_kakao.svg
  img/ic_twitter.svg
  img/ic_youtube.svg
  img/logo.svg
  img/logo_mobile.svg
  img/open_graph.png
  index.html
  items/index.html
  js/login.js
  js/modules/eyeIcon.js
  js/modules/userData.js
  js/modules/validation.js
  js/modules/var.js
  js/signup.js
  login/index.html
  privacy/index.html
  signup/index.html
  style/auth.css
  style/global.css
  style/main.css
Labels: 매운맛🔥

#5 [탁우현] sprint 1, sprint 2
  README.md
  css/media.css
  css/modal.css
  css/style.css
  css/userPage.css
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/btn_visibility_on_24px.png
  image/googleicon.png
  image/ic_facebook.png
  image/ic_instagram.png
  image/ic_twitter.png
  image/ic_youtube.png
  image/kakaoicon.png
  image/logo.png
  image/mainlogo.png
  image/mb_logo.png
  index.html
  nav/faq.html
  nav/items.html
  nav/privacy.html
  script/main.js
  script/regex.js
  script/stylejs.js
  users/login.html
  users/singup.html
Labels: 매운맛🔥

#13 [김소희] sprint1+sprint2
  pandamarket_kimsohee/README.md
  pandamarket_kimsohee/create_account.html
  pandamarket_kimsohee/html/FAQ.html
  pandamarket_kimsohee/html/bulletin.html
  pandamarket_kimsohee/html/facebook.html
  pandamarket_kimsohee/html/instargram.html
  pandamarket_kimsohee/html/items.html
  pandamarket_kimsohee/html/login.html
  pandamarket_kimsohee/html/privacy.html
  pandamarket_kimsohee/html/used.html
  pandamarket_kimsohee/html/x.html
  pandamarket_kimsohee/html/youtube.html
  pandamarket_kimsohee/images/google.png
  pandamarket_kimsohee/images/ic_facebook.png
  pandamarket_kimsohee/images/ic_instagram.png
  pandamarket_kimsohee/images/ic_twitter.png
  pandamarket_kimsohee/images/ic_youtube.png
  pandamarket_kimsohee/images/kakaotalk.png
  pandamarket_kimsohee/images/구매원하는 상품.png
  pandamarket_kimsohee/images/비밀번호눈.png
  pandamarket_kimsohee/images/일상 모든 물건거래.png
  pandamarket_kimsohee/images/판다 옷.png
  pandamarket_kimsohee/images/판다마켓 로그인 페이지.JPG
  pandamarket_kimsohee/images/판다마켓 회원가입 페이지.JPG
  pandamarket_kimsohee/images/판다마켓.png
  pandamarket_kimsohee/images/판다마켓_로고.png
  pandamarket_kimsohee/images/판다마켓_홈페이지.JPG
  pandamarket_kimsohee/images/판매원하는 상품.png
  pandamarket_kimsohee/images/하단 판다친구들.png
  pandamarket_kimsohee/index.html
  pandamarket_kimsohee/login.html
  pandamarket_kimsohee/panda_login.html
  pandamarket_kimsohee/reset.css
  pandamarket_kimsohee/style.css
  pandamarket_kimsohee/style_home.css
Labels: 매운맛🔥

#37 [박상훈] Sprint3
  README.md
  faq.html
  imgs/favicon.ico
  imgs/panda_market_logo.png
  imgs/panda_mobile_log.png
  index.html
  index.js
  items.html
  login.html
  login.js
  modules/alert.js
  modules/userData.js
  modules/validate.js
  signup.html
  signup.js
  style.css
Labels: 매운맛🔥

#44 [임송이] Sprint 3
  .gitignore
  faq/index.html
  index.html
  items/index.html
  js/login.js
  js/modules/eyeIcon.js
  js/modules/userData.js
  js/modules/validation.js
  js/modules/var.js
  js/signup.js
  login/index.html
  privacy/index.html
  signup/index.html
  style/auth.css
  style/main.css
Labels: 매운맛🔥

#36 [김현우] Sprint3
  Script/data.js
  Script/login.js
  Script/login_js.js
  Script/signup.js
  Script/signup_js.js
  Script/validationLogin.js
  Script/validationSignup.js
  Script/validation_signup.js
  code.env
  index.html
  items/index.html
  login/index.html
  login/style_login.css
  netlify.txt
  signup/index.html
  signup/style_signup.css
  style.css
Labels: 매운맛🔥

#35 [김효인] Sprint3
  .DS_Store
  README.md
  css/login.css
  css/main.css
  css/signup.css
  css/singup.css
  css/style.css
  css/varibless.css
  img/index_img/Group 19.png
  img/index_img/Img_home_01.png
  img/index_img/Img_home_02.png
  img/index_img/Img_home_03.png
  img/index_img/Img_home_bottom.png
  img/index_img/Img_home_top (2).png
  img/index_img/ic_facebook.png
  img/index_img/ic_instagram.png
  img/index_img/ic_twitter.png
  img/index_img/ic_youtube.png
  img/index_img/logo.png
  img/index_img/web_logo.png
  img/login_img/Component 2.png
  img/login_img/Component 3.png
  img/login_img/logo.png
  index.html
  js/login.js
  js/login_signup.js
  js/signup.js
  js/singnup.js
  login.html
  signup.html
  singnup.html
Labels: 매운맛 🔥

#47 [송영섭] sprint 3
  mission/Lib/public.js
  mission/Lib/user_data.js
  mission/img/Img_hot_item.png
  mission/img/Img_hot_item.png:Zone.Identifier
  mission/img/Img_register.png
  mission/img/Img_register.png:Zone.Identifier
  mission/img/Img_search.png
  mission/img/Img_search.png:Zone.Identifier
  mission/img/Panda_bottom.png
  mission/img/Panda_bottom.png:Zone.Identifier
  mission/img/Panda_logo.png
  mission/img/Panda_logo.png:Zone.Identifier
  mission/img/banner.png
  mission/img/banner.png:Zone.Identifier
  mission/index.html
  mission/items/index.html
  mission/login/img/ic_google.png
  mission/login/img/ic_google.png:Zone.Identifier
  mission/login/img/ic_kakao.png
  mission/login/img/ic_kakao.png:Zone.Identifier
  mission/login/index.html
  mission/login/login_public.css
  mission/login/mobile_style.css
  mission/login/script.js
  mission/login/style.css
  mission/main_public.css
  mission/mobile_style.css
  mission/pc_style.css
  mission/signup/img/ic_google.png
  mission/signup/img/ic_google.png:Zone.Identifier
  mission/signup/img/ic_kakao.png
  mission/signup/img/ic_kakao.png:Zone.Identifier
  mission/signup/index.html
  mission/signup/mobile_style.css
  mission/signup/script.js
  mission/signup/signup_public.css
  mission/signup/style.css
  mission/singup_login.css
  mission/tablet_style.css
Labels: 매운맛 🔥

#40 [김민서] sprint3
  README.md
  common_js/login_signup.js
  common_style/login_signup-style.css
  html/faq.html
  html/items.html
  html/login.html
  html/privacy.html
  html/signup.html
  image/google.svg
  image/ic_facebook.png
  image/ic_instagram.png
  image/ic_twitter.png
  image/ic_youtube.png
  image/invisible.svg
  image/kakao.svg
  image/logo@3x.png
  image/visible.svg
  image/구매원하는상품을확인하세요.png
  image/믿을수있는판다마켓.png
  image/인기상품을활용해보세요.png
  image/판다_배경사진.png
  image/판다마켓로고.png
  image/판매를원하는상품을등록하세요.png
  index.html
  js/login.js
  js/signup.js
  js/visibility.js
  login-style.css
  signup-style.css
  style.css
  style/login-style.css
  style/reset.css
  style/signup-style.css
  style/style.css
Labels: 매운맛 🔥

#41 [박명준] sprint3
  .github/pull-request-template.md
Labels: 매운맛 🔥
