Repository codeit-sprint-fullstack/1-Sprint-Mission-FE, pull requests merged in 2024-08, with the labels that each got.

#86 [이율리] sprint 5
  .github/pull-request-template.md
  .gitignore
  config-overrides.js
  package-lock.json
  package.json
  public/face.png
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.test.js
  src/assets/img/btn_registProduct.png
  src/assets/img/ic_search.png
  src/assets/img/logo-face.png
  src/assets/img/logo.png
  src/assets/img/user.svg
  src/assets/styles/App.css
  src/assets/styles/Header.css
  src/assets/styles/index.css
  src/assets/styles/reset.css
  src/components/Dropdown.js
  src/components/Header.js
  src/components/PagingButton.js
  src/components/ProductList.js
  src/components/SearchProduct.js
  src/constants/path.js
  src/hooks/useData.js
  src/index.js
  src/reportWebVitals.js
  src/services/ProductService.js
  src/utils/utils.js
Labels: 최종 제출

#80 [박상훈] sprint5
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/Main.js
  src/api.js
  src/assets/imgs/ic_sort.png
  src/assets/imgs/logo.png
  src/assets/imgs/logo_mobile.png
  src/assets/imgs/profile.png
  src/components/App.js
  src/components/Nav.css
  src/components/Nav.js
  src/components/ProductList.css
  src/components/ProductList.js
  src/components/SelectBox.css
  src/components/SelectBox.js
  src/components/useMediaQuery.js
  src/components/useProducts.js
  src/index.css
  src/index.js
Labels: 매운맛 🔥

#95 React 박성현 sprint5
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/App.js
  src/assets/images/btn_left.png
  src/assets/images/btn_right.png
  src/assets/images/btn_sort.png
  src/assets/images/ic_arrow_down.png
  src/assets/images/ic_facebook.png
  src/assets/images/ic_heart.png
  src/assets/images/ic_instagram.png
  src/assets/images/ic_search.png
  src/assets/images/ic_twitter.png
  src/assets/images/ic_youtube.png
  src/assets/images/logo-pic.png
  src/assets/images/logo-text.png
  src/assets/images/user.png
  src/assets/services/api.mjs
  src/assets/styles/reset.css
  src/assets/styles/style.css
  src/components/BestProduct/BestProduct.js
  src/components/BestProduct/bestproduct.css
  src/components/Footer/Footer.js
  src/components/Footer/footer.css
  src/components/Header/Header.js
  src/components/Header/header.css
  src/components/Nav/DropDown/DropDown.js
  src/components/Nav/DropDown/dropDown.css
  src/components/Nav/Nav.js
  src/components/Nav/RegistProduct/RegistProduct.js
  src/components/Nav/RegistProduct/registProduct.css
  src/components/Nav/SearchForm/SearchForm.js
  src/components/Nav/SearchForm/searchform.css
  src/components/Nav/nav.css
  src/components/Pagination/Pagination.js
  src/components/Pagination/pagination.css
  src/components/SellProduct/SellProduct.js
  src/components/SellProduct/sellproduct.css
  src/hook/usePageSize.js
  src/index.js
Labels: 최종 제출

#75 [탁우현] sprint 5
  .github/pull-request-template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  public/robots.txt
  src/Main.js
  src/api.js
  src/components/App.js
  src/components/footer.js
  src/components/header.js
  src/components/paging.js
  src/components/productlist.js
  src/components/search.js
  src/css/app.css
  src/css/footer.css
  src/css/header.css
  src/css/paging.css
  src/css/products.css
  src/css/reset.css
  src/css/serach.css
  src/hooks/Returnresize.js
  src/hooks/resize.js
  src/image/Img_home_01.png
  src/image/Img_home_02.png
  src/image/Img_home_03.png
  src/image/Img_home_bottom.png
  src/image/Img_home_top.png
  src/image/Polygon.png
  src/image/Vector.png
  src/image/arrow_left.png
  src/image/arrow_right.png
  src/image/btn_visibility_on_24px.png
  src/image/favoriteIcon.png
  src/image/googleicon.png
  src/image/ic_arrow_down.png
  src/image/ic_facebook.png
  src/image/ic_heart.png
  src/image/ic_instagram.png
  src/image/ic_search.png
  src/image/ic_sort.png
  src/image/ic_twitter.png
  src/image/ic_youtube.png
  src/image/kakaoicon.png
  src/image/logo.png
  src/image/mainlogo.png
  src/image/mb_logo.png
  src/index.js
  src/mockData.json
  src/pages/Faq.js
  src/pages/Home.js
  src/pages/Privacy.js
Labels: 매운맛 🔥, 최종 제출

#79 [임송이] Sprint 5
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.svg
  public/index.html
  src/App.jsx
  src/assets/arrow_right.svg
  src/assets/ic_arrow_down.svg
  src/assets/ic_heart.svg
  src/assets/ic_search.svg
  src/assets/ic_sort.svg
  src/assets/logo.svg
  src/assets/logo_mobile.svg
  src/assets/profile_icon.svg
  src/components/BestSection/BestSection.css
  src/components/BestSection/BestSection.jsx
  src/components/DropDown/DropDown.css
  src/components/DropDown/DropDown.jsx
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/Nav/Nav.css
  src/components/Nav/Nav.jsx
  src/components/Pagination/Pagination.css
  src/components/Pagination/Pagination.jsx
  src/components/ProductList/ProductList.css
  src/components/ProductList/ProductList.jsx
  src/components/ProductSection/ProductSection.css
  src/components/ProductSection/ProductSection.jsx
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.jsx
  src/components/Wrapper/Wrapper.css
  src/components/Wrapper/Wrapper.jsx
  src/global.css
  src/hooks/useMediaQuery.jsx
  src/index.jsx
  src/pages/ProductPage.css
  src/pages/ProductPage.jsx
  src/pages/TempPages.jsx
  src/services/api.jsx
Labels: 매운맛 🔥, 최종 제출

#81 [김민서] sprint5
  .github/pull-request-template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  README.md
  README.old.md
  package-lock.json
  package.json
  public/image/btn_sort.svg
  public/image/circle.svg
  public/image/down.svg
  public/image/glass.svg
  public/image/heart.svg
  public/image/left.svg
  public/image/logo.svg
  public/image/mobile_logo.svg
  public/image/profile.svg
  public/image/right.svg
  public/index.html
  src/App.css
  src/App.js
  src/components/Navbar.css
  src/components/Navbar.js
  src/components/ProductCard.css
  src/components/ProductCard.js
  src/components/ProductList.css
  src/components/ProductList.js
  src/hooks/useFetchProducts.js
  src/hooks/useScreenType.js
  src/index.css
  src/index.js
Labels: 최종 제출

#92 [고종민] sprint5
  .github/pull-request-template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  .netlify/state.json
  README.md
  package-lock.json
  package.json
  public/index.html
  screenshot/product_desktop.JPG
  screenshot/product_mobile.JPG
  screenshot/product_tablet.JPG
  src/App.css
  src/App.js
  src/api.js
  src/components/BestProducts.js
  src/components/Footer.js
  src/components/Navigation.js
  src/components/Product.js
  src/components/SaleProducts.js
  src/hooks/usePageSize.js
  src/images/arrowDownIcon.png
  src/images/favoriteEmptyHeart-small.png
  src/images/favoriteFullHeart-small.png
  src/images/pandaLogo.png
  src/images/pandaLogo_small.png
  src/images/searchIcon.png
  src/images/sortIcon.png
  src/images/userIcon.png
  src/index.js
  src/styles/BestProducts.css
  src/styles/Footer.css
  src/styles/Navigation.css
  src/styles/Product.css
  src/styles/SaleProducts.css
  src/styles/reset.css
Labels: 최종 제출

#74 [김현우] Mission5
  .gitignore
  .vscode/settings.json
  jsconfig.json
  package-lock.json
  package.json
  public/index.html
  src/API/ArticleService.js
  src/API/ProductService.js
  src/assets/images/arrow.png
  src/assets/images/ic-heart.png
  src/assets/images/ic-search.png
  src/assets/images/ic-sort.png
  src/assets/images/logo-small.svg
  src/assets/images/logo.png
  src/assets/images/upside-arrow.png
  src/assets/images/user-basic-profile.png
  src/assets/styles/App.css
  src/assets/styles/reset.css
  src/components/GNB.js
  src/components/ProductCard.js
  src/components/sortOptionDropdown.js
  src/components/sortOptionDropdownSmall.js
  src/hooks/usePageSize.js
  src/hooks/useViewportSize.js
  src/index.js
  src/pages/Product/bestSellingProducts.js
  src/pages/Product/constants.js
  src/pages/Product/keywordSearch.js
  src/pages/Product/paginationButtons.js
  src/pages/Product/productManagement.js
  src/pages/Product/productManagementSmall.js
  src/pages/Product/sellingProducts.js
Labels: 매운맛 🔥, 최종 제출

#77 [주영은] sprint5
  .github/pull-request-template.md
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.jsx
  src/BestList/BestList.css
  src/BestList/BestList.jsx
  src/NavBar/NavBar.css
  src/NavBar/NavBar.jsx
  src/Pagination/Pagination.css
  src/Pagination/Pagination.jsx
  src/Sell/CustomDropdown.jsx
  src/Sell/DesktopSearchBar.jsx
  src/Sell/MobileSearchBar.jsx
  src/Sell/SellList.css
  src/Sell/SellList.jsx
  src/common/Util.js
  src/common/useDeviceType.js
  src/common/useFetchProducts.js
  src/image/ic_arrow_down.svg
  src/image/ic_profile.svg
  src/image/ic_search.svg
  src/image/ic_sort.svg
  src/image/img_logo.svg
  src/image/logo.svg
  src/index.js
Labels: 매운맛 🔥, 최종 제출

#87 [김효인] sprint5
  .github/pull-request-template.md
  .gitignore
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  public/index.html
  src/Main.js
  src/api/ProductService.js
  src/components/Container.js
  src/components/Container.module.css
  src/components/Dropdown.js
  src/components/Dropdown.module.css
  src/components/Layout.js
  src/components/Nav.js
  src/components/Nav.module.css
  src/components/Pagination.js
  src/components/Pagination.module.css
  src/components/ProductBestList.js
  src/components/ProductBestList.module.css
  src/components/ProductList.js
  src/components/ProductList.module.css
  src/components/ProductListHeader.js
  src/components/ProductListHeader.module.css
  src/css/reset.css
  src/hook/useMediaType.js
  src/img/mobile_arrow.png
  src/img/mobile_logo.png
  src/img/nav_login_icon.png
  src/img/nav_logo.png
  src/index.js
  src/pages/MarketPage.js
  src/pages/MarketPage.module.css
Labels: 매운맛 🔥, 최종 제출

#94 [정준호] sprint5
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api/getProductsData.js
  src/components/HomepageRenderFooter.css
  src/components/HomepageRenderFooter.js
  src/components/HomepageRenderHeader.css
  src/components/HomepageRenderHeader.js
  src/components/ProductHeaderRegistBtn.css
  src/components/ProductHeaderRegistBtn.js
  src/components/ProductHeaderSearchBar.css
  src/components/ProductHeaderSearchBar.js
  src/components/ProductHeaderSortBtn.css
  src/components/ProductHeaderSortBtn.js
  src/components/ProductHeaderText.css
  src/components/ProductHeaderText.js
  src/components/ProductRender.css
  src/components/ProductRender.js
  src/components/ProductRenderGrid.css
  src/components/ProductRenderGrid.js
  src/components/ProductRenderHeader.css
  src/components/ProductRenderHeader.js
  src/hooks/_TEMP_useProductDatacopy.js
  src/hooks/_TEMP_useProductTotalSize copy.js
  src/hooks/useControlPage.js
  src/hooks/useProductData.js
  src/hooks/useWindowWidhtSize.js
  src/images/icon/ic_arrow_down.svg
  src/images/icon/ic_heart.svg
  src/images/icon/ic_search.svg
  src/images/logo.svg
  src/images/profile.svg
  src/index.css
  src/index.js
  src/pages/Homepage.css
  src/pages/Homepage.js
  src/reportWebVitals.js
  src/setupTests.js
  x
Labels: 매운맛 🔥, 최종 제출

#89 [박명준] sprint5
  .github/pull-request-template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  src/api.js
  src/component/App.css
  src/component/App.js
  src/component/Best.css
  src/component/Best.js
  src/component/Nav.css
  src/component/Nav.js
  src/component/OnSale.css
  src/component/OnSale.js
  src/component/OnSaleDropDown.css
  src/component/OnSaleDropDown.js
  src/component/Pagination.css
  src/component/Pagination.js
  src/component/Registration.css
  src/component/Registration.js
  src/image/dropDownArrow.png
  src/image/logo.png
  src/image/mobileDropDown.png
  src/image/mobileLogo.png
  src/image/searchIcon.png
  src/image/userIcon.png
  src/index.js
Labels: 매운맛 🔥, 최종 제출

#76 [김민수] sprint 5
  .gitignore
  .vscode/launch.json
  README.md
  package-lock.json
  package.json
  public/index.html
  src/app.js
  src/header.css
  src/header.js
  src/img/Header_logo.svg
  src/img/Header_my.svg
  src/img/search.svg
  src/img/sort.svg
  src/index.js
  src/main.css
  src/main.js
  src/reset.css
Labels: 매운맛 🔥, 최종 제출

#88 [안재민] sprint5
  .github/pull-request-template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/App.test.js
  src/api.js
  src/component/Dropdown.js
  src/component/Items.css
  src/component/Items.js
  src/component/Nav.css
  src/component/Nav.js
  src/component/Templete.js
  src/component/pageButton.js
  src/hooks/useResponsive.js
  src/img/before-page-img.png
  src/img/drop-down-mobile.png
  src/img/drop-down.png
  src/img/favorite.png
  src/img/logo.png
  src/img/my-logo.png
  src/img/next-page-img.png
  src/img/no-img.png
  src/img/search.png
  src/img/small-logo.png
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/reset.css
Labels: 매운맛 🔥, 최종 제출

#109 [송영섭] mission6
  .gitignore
  react-mission/package-lock.json
  react-mission/package.json
  react-mission/src/MainRender.js
  react-mission/src/api/api.js
  react-mission/src/components/App.css
  react-mission/src/components/App.js
  react-mission/src/components/BestProduct.css
  react-mission/src/components/BestProduct.js
  react-mission/src/components/Footer.css
  react-mission/src/components/Footer.js
  react-mission/src/components/Header.css
  react-mission/src/components/Header.js
  react-mission/src/components/Main.js
  react-mission/src/components/Nav.css
  react-mission/src/components/Nav.js
  react-mission/src/components/OrderChange.css
  react-mission/src/components/OrderChange.js
  react-mission/src/components/Pagination.css
  react-mission/src/components/ProductCard.css
  react-mission/src/components/ProductCard.js
  react-mission/src/components/Registration.css
  react-mission/src/components/Registration.js
  react-mission/src/components/RegistrationForm.css
  react-mission/src/components/RegistrationForm.js
  react-mission/src/components/SaleProduct.css
  react-mission/src/components/SaleProduct.js
  react-mission/src/components/SearchForm.css
  react-mission/src/components/SearchForm.js
  react-mission/src/components/api.js
  react-mission/src/components/hook/useRegistationBlur.js
  react-mission/src/components/img/marketDefaultImg.png
  react-mission/src/components/img/tagDeleteImg.png
  react-mission/src/components/mobileStyle.css
  react-mission/src/components/pcStyle.css
  react-mission/src/components/publicStyle.css
  react-mission/src/components/reset.css
  react-mission/src/components/tablitStyle.css
  react-mission/src/index.js
  react-mission/src/pages/HomePage.js
  react-mission/src/pages/ParticularPage.js
  react-mission/src/pages/Registration.css
  react-mission/src/pages/Registration.js
  react-mission/src/pages/SecondHandMarket.css
  react-mission/src/pages/SecondHandMarket.js
Labels: 매운맛 🔥, 최종 제출

#108 [박명준] sprint6
  readme.md
  src/api.js
  src/component/App.css
  src/component/App.js
  src/component/Best.css
  src/component/Best.js
  src/component/ItemForm.css
  src/component/ItemForm.js
  src/component/Nav.css
  src/component/Nav.js
  src/component/OnSale.css
  src/component/OnSale.js
  src/component/OnSaleDropDown.css
  src/component/ProductDetail.js
  src/component/Registration.css
  src/component/Registration.js
  src/image/defaultImg.png
  src/image/tagDelete.png
  src/useValidation.js
Labels: 매운맛 🔥, 최종 제출

#104 [임송이] sprint 6
  README.md
  src/App.jsx
  src/assets/ic_X.svg
  src/assets/img_default.svg
  src/components/BestSection/BestSection.css
  src/components/BestSection/BestSection.jsx
  src/components/Header/Header.jsx
  src/components/Nav/Nav.jsx
  src/components/ProductList/ProductList.css
  src/components/ProductList/ProductList.jsx
  src/components/ProductSection/ProductSection.css
  src/components/ProductSection/ProductSection.jsx
  src/components/Registration/InputContainer.css
  src/components/Registration/InputContainer.jsx
  src/components/Registration/RegistrationForm.css
  src/components/Registration/RegistrationForm.jsx
  src/components/Registration/TagInput.css
  src/components/Registration/TagInput.jsx
  src/components/SearchBar/SearchBar.css
  src/components/Wrapper/Wrapper.css
  src/global.css
  src/index.js
  src/pages/Pages.css
  src/pages/ProductPage.jsx
  src/pages/RegistrationPage.jsx
  src/pages/TempPages.css
  src/pages/TempPages.jsx
  src/services/api.js
  src/services/api.jsx
Labels: 매운맛 🔥

#99 [박상훈] sprint6
  README.md
  package-lock.json
  package.json
  public/index.html
  src/Main.js
  src/api.js
  src/assets/imgs/ic_X.svg
  src/assets/imgs/img_default.svg
  src/components/App.jsx
  src/components/Nav.css
  src/components/Nav.js
  src/components/Nav.jsx
  src/components/Pagination.css
  src/components/Pagination.jsx
  src/components/ProductList.css
  src/components/ProductList.js
  src/components/ProductList.jsx
  src/components/SelectBox.css
  src/components/SelectBox.js
  src/components/SelectBox.jsx
  src/components/useProducts.js
  src/hook/useFormValidation.jsx
  src/hook/useMediaQuery.jsx
  src/hook/useProducts.jsx
  src/pages/BoardPage.jsx
  src/pages/HomePage.jsx
  src/pages/ProductDetailPage.jsx
  src/pages/RegistrationPage.css
  src/pages/RegistrationPage.jsx
Labels: 매운맛 🔥

#103 [김현우] sprint6
  .env
  package-lock.json
  package.json
  src/API/week6API.js
  src/App.js
  src/assets/images/img-default.png
  src/assets/images/removal-icon.png
  src/assets/styles/App.css
  src/assets/styles/reg.css
  src/assets/styles/reset.css
  src/components/GNB.js
  src/components/ProductCard.js
  src/hooks/UseArticleValidation.js
  src/index.js
  src/pages/Product/productMainPage.js
  src/pages/Product/productManagement.js
  src/pages/ProductRegstration/regMainPage.js
  src/pages/ProductRegstration/registration.js
  src/pages/SecondHand/SecondHandMainPage.js
  src/pages/SecondHand/mockItems.js
Labels: 매운맛 🔥

#111 [고종민] sprint6
  .env
  README.md
  package-lock.json
  package.json
  screenshot/market_page.JPG
  screenshot/register_page.JPG
  src/App.js
  src/api.js
  src/components/BestProducts.js
  src/components/Navigation.js
  src/components/Product.js
  src/components/ProductDetail.js
  src/components/Registration.js
  src/components/SaleProducts.js
  src/hooks/useFormValid.js
  src/images/panda_image.png
  src/styles/BestProducts.css
  src/styles/Navigation.css
  src/styles/Registration.css
  src/styles/SaleProducts.css
Labels: 최종 제출

#102 [김민서] sprint6
  .env
  .gitignore
  package-lock.json
  package.json
  public/image/img_default.svg
  public/index.html
  src/App.js
  src/components/Navbar.css
  src/components/Navbar.js
  src/components/ProductCard.css
  src/components/ProductCard.js
  src/components/ProductDetail.js
  src/components/ProductList.js
  src/components/Registration.css
  src/components/Registration.js
  src/hooks/useFetchProducts.js
  src/hooks/useValidation.js
Labels: 매운맛 🔥, 최종 제출

#98 [주영은] sprint6
  .gitignore
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/BestList/BestList.css
  src/BestList/BestList.jsx
  src/NavBar/NavBar.css
  src/NavBar/NavBar.jsx
  src/Pagination/Pagination.css
  src/Pagination/Pagination.jsx
  src/Product/Product.css
  src/Product/Product.jsx
  src/Registration/ProductAddForm.css
  src/Registration/ProductAddForm.jsx
  src/Registration/Registration.css
  src/Registration/Registration.jsx
  src/Registration/createProduct.js
  src/Sell/CustomDropdown.jsx
  src/Sell/DesktopSearchBar.jsx
  src/Sell/MobileSearchBar.jsx
  src/Sell/SellList.css
  src/Sell/SellList.jsx
  src/common/useFetchProducts.js
  src/common/useValidation.js
  src/image/img_default.svg
Labels: 매운맛 🔥, 최종 제출

#101 [김민수] sprint 6
  .DS_Store
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/.DS_Store
  src/app.js
  src/header.css
  src/header.js
  src/img/.DS_Store
  src/img/HeaderLogo2.svg
  src/img/스크린샷 2024-08-09 오전 9.47.31.png
  src/img/스크린샷 2024-08-09 오전 9.48.13.png
  src/img/스크린샷 2024-08-09 오전 9.49.29.png
  src/main.css
  src/main.js
  src/registration.css
  src/registration.js
Labels: 매운맛 🔥, 최종 제출

#107 [안재민] sprint6
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/App.test.js
  src/api.js
  src/component/Dropdown.js
  src/component/Items.css
  src/component/Items.js
  src/component/Main.js
  src/component/Nav.css
  src/component/Nav.js
  src/component/PageButton.js
  src/component/Registration.css
  src/component/Registration.js
  src/component/Router.js
  src/component/Templete.js
  src/env.js
  src/hooks/useValidateText.js
  src/img/delete-button.png
  src/index.js
Labels: 매운맛 🔥, 최종 제출
